dist: trusty
sudo: required
language: java

os: linux

env: V=0.28.1

addons:
  sauce_connect: true

before_install:
  - |
    OS=linux
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
    - |
      FILTERS="-notravis,-noci"
      if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
        FILTERS="${FILTERS},-sauce"
      fi
      bazel \
      --output_base="${HOME}/.cache/bazel" \
      test \
      --test_tag_filters="${FILTERS}" \
      --test_output=streamed \
      --test_env=TUNNEL_IDENTIFIER="${TRAVIS_JOB_NUMBER}" \
      --test_env=BUILD_TAG="${TRAVIS_COMMIT}" \
      //...
